language: java

jdk: openjdk8

env: DISPLAY=:99.0

services:
    - docker

install: true

cache:
    directory:
        - $HOME/.m2

before_script:
   - sh -e /etc/init.d/xvfb start

script:
    - mvn clean verify
