language: java

jdk: openjdk8

# lock distro for gui test
dist: xenial

services:
    - docker
    - xvfb # enable DISPLAY

install: true

cache:
    directory:
        - $HOME/.m2

script:
    - mvn clean verify

