language: java

jdk: openjdk8

# lock distro for gui test
dist: xenial

services:
    - docker
    - xvfb # enable DISPLAY

job:
    include:
        - if: branch = master
          env: SONAR="sonar:sonar"

addons:
  sonarcloud:
    organization: "federicapaoli1"
    token:
      secure: $SONAR_TOKEN

install: true

cache:
    directories:
        - $HOME/.m2
        - $HOME/.sonar/cache


script:
    - mvn clean verify -Pjacoco $SONAR
