language: java

jdk: openjdk8

env: DISPLAY=:99.0

services:
    - docker
    - xvfb

install: true

cache:
    directory:
        - $HOME/.m2

before_script:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - sleep 3

script:
    - mvn clean verify
